all:
	pip3 install -e . --user
	python3 example.py

clean:
	rm -rf build/ tmp/ python/decision_tree_module/decision_tree_pybind.cpython-37m-x86_64-linux-gnu.so python/decision_tree_module/decision_tree.egg-info/

